### ISSUE TITLE
[!] atom-pandoctools initial release

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/atom-pandoctools#1]
* Reusing MPP https://github.com/atom-community/markdown-preview-plus/issues/322
* https://github.com/atom-community/markdown-preview-plus/issues/441
* https://github.com/atom-community/markdown-preview-plus/issues/443

# Fix MPP

* [x] ~[Image size bug in MPP](https://github.com/atom-community/markdown-preview-plus/issues/405)~
* [ ] [Save As PDF makes font colors darker](https://github.com/atom-community/markdown-preview-plus/issues/393)
* [ ] [Empty lines in code blocks dissapper](https://github.com/atom-community/markdown-preview-plus/issues/398)
* [ ] Check cross-references links

https://github.com/atom-community/markdown-preview-plus/blob/master/CONTRIBUTING.md

# Tune MPP

* [x] ~do not forget about [this](https://github.com/kiwi0fruit/misc/commit/70609c253629c09d51dc35076e69755d31d2d869) - add font settings to GUI~
* [x] check if [code highlighter spaces problem](https://github.com/atom-haskell/atom-highlights/pull/1) is solved
* [x] check if `data:image/`now works
* [x] find out how to tune MathJax and tune it
* [x] fix main .less file. Move fonts definitions there too and take into account  changes:
    `.markdown-preview:not([data-use-github-style])` ->  
    `markdown-preview-plus-view:not([data-use-github-style])` changes
* [x] `@mjx-mono-font-size: 80%;`
* [ ] ~enhance [PDF print](https://github.com/atom-community/markdown-preview-plus/issues/397)~
  * ~.pdf.7z~
      * ~.phone.pdf~
      * ~.tablet.pdf~
      * ~.desktop.pdf~
      * ~.A4.pdf~
* [ ] No multiple pdf. Have one that looks good on tablet, good on smartphone horizontal. Images and tables are of the same size as text nody. But if I set style to 100% the table would take all horizontal space (which is wider that text body). 70 ch. width? 30 em?

* [ ] add [MPP Patch](https://github.com/kiwi0fruit/misc/tree/master/mpp) to atom-pandoctools

**Comment by kiwi0fruit** [comment]
```less
@import 'pandoctools.less';
@main-font: "Libertinus Serif", serif;

.markdown-preview-plus-styles() {
  .pandoctools();
}
```

```less
@main-font: "Segoe UI", sans-serif;

.pandoctools() {
   .sourceCode {
    background-color: hsl(180, 24%, 90%) !important;
  }
  * {
    color: blue !important;
  }
  body {
    font-family: @main-font;
  }
}

```
```less
.markdown-preview-plus-styles() {}
@import (optional) '../../../styles.less';
// very end:
.markdown-preview-plus-styles();
```

**Comment by kiwi0fruit** [comment]
```js
  // if `pandoctools_integration` package option:
  //     if file `api-pandoctools.less` not exists:
  //         create file `api-pandoctools.less` from template
  //         (with abs path to ~/.atom/packages/atom-pandoctools/styles.less)
  //     styles.push(getClientStyle('api-pandoctools.less'))
  // if file `api-styles.less` not exists:
  //     create file `api-styles.less` from template
  //     (with abs path to ~/.atom/styles.less)
  // styles.push(getClientStyle('api-styles.less'))
```
